/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UTS;

/**
 *
 * @author Dwi
 */
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

//JFrame adalah jendela utama aplikasi
public class GUIMahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form GUIMahasiswa
     */
    private PengelolaData pengelola;
    String nimdata;
    String namadata;
    double ipk;

    public GUIMahasiswa() {
        initComponents();
        pengelola = new MahasiswaService();

    }

    private void tampilkanData() {
        // Ambil model tabel
        DefaultTableModel model = (DefaultTableModel) tabel.getModel();

        // Kosongkan tabel dulu (biar tidak dobel)
        model.setRowCount(0);   

        // Loop data dari ArrayList
        for (Mahasiswa m : pengelola.getDaftarMahasiswa()) {

            String tipe;
            int jumlahOrg;

            if (m instanceof MahasiswaAktif) {
                MahasiswaAktif a = (MahasiswaAktif) m;
                tipe = a.getStatusAktif();   // atau "Mahasiswa Aktif"
                jumlahOrg = a.getJumlahOrganisasi();
            } else {
                tipe = "Mahasiswa";
                jumlahOrg = 0;
            }

            // Tambahkan ke JTable
            model.addRow(new Object[]{
                m.getNim(),
                m.getNama(),
                m.getIpk(),
                m.getPredikat(),
                tipe,
                jumlahOrg
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nim_f = new javax.swing.JTextField();
        nama = new javax.swing.JLabel();
        nama_f = new javax.swing.JTextField();
        nama1 = new javax.swing.JLabel();
        ipk_f = new javax.swing.JTextField();
        nama2 = new javax.swing.JLabel();
        Tipe = new javax.swing.JComboBox<>();
        nama3 = new javax.swing.JLabel();
        txtOrg = new javax.swing.JSpinner();
        Simpan = new javax.swing.JButton();
        Lihatdata = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NIM");

        nama.setText("NAMA");

        nama1.setText("IPK");

        nama2.setText("TIPE");

        Tipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mahasiswa Organisasi", "Mahasiswa" }));

        nama3.setText("JUMLAH ORGANISASI");

        Simpan.setText("Simpan");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });

        Lihatdata.setText("Lihat");
        Lihatdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LihatdataActionPerformed(evt);
            }
        });

        jLabel2.setText("SURVEI DATA AKADEMIK MAHASISWA DAN MAHASISWA AKTIF ORGANISASI");

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "NAMA", "IPK", "PREDIKAT", "Status", "Jumlah Organisasi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Lihatdata)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nama1)
                                    .addComponent(nama)
                                    .addComponent(jLabel1)
                                    .addComponent(nama2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nama_f, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ipk_f, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Tipe, 0, 444, Short.MAX_VALUE)
                                    .addComponent(nim_f)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nama3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nim_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ipk_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama2)
                    .addComponent(Tipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama3)
                    .addComponent(txtOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Simpan)
                    .addComponent(Lihatdata))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        // TODO add your handling code here:
        nimdata = nim_f.getText();
        namadata = nama_f.getText();
        ipk = Double.parseDouble(ipk_f.getText());
        System.out.println("-------------------------------------------################ ");
        int jumlahOrg = (int) txtOrg.getValue();
        Mahasiswa mhs;

        // POLYMORPHISM
        if (jumlahOrg > 0) {
            mhs = new MahasiswaAktif(nimdata, namadata, ipk, jumlahOrg);
        } else {
            mhs = new Mahasiswa(nimdata, namadata, ipk);
        }

        pengelola.tambahData(mhs);

        // TAMPILKAN STATUS AKTIVIS
        if (mhs instanceof MahasiswaAktif) {
            MahasiswaAktif a = (MahasiswaAktif) mhs;
        }

        JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
    }//GEN-LAST:event_SimpanActionPerformed

    private void LihatdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LihatdataActionPerformed
        // TODO add your handling code here:
        tampilkanData();
    }//GEN-LAST:event_LihatdataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Lihatdata;
    private javax.swing.JButton Simpan;
    private javax.swing.JComboBox<String> Tipe;
    private javax.swing.JTextField ipk_f;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nama1;
    private javax.swing.JLabel nama2;
    private javax.swing.JLabel nama3;
    private javax.swing.JTextField nama_f;
    private javax.swing.JTextField nim_f;
    private javax.swing.JTable tabel;
    private javax.swing.JSpinner txtOrg;
    // End of variables declaration//GEN-END:variables
}
